version: '3'
services:
  stmina-clinic-db:
    platform: linux/x86_64
    networks:
      - new
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'stminaclinic'
      MYSQL_PASSWORD: 'angelmichael'
      MYSQL_ROOT_PASSWORD: 'angelmichael'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./stmina-clinic-db:/var/lib/mysql
  stminaclinic-server:
    platform: linux/x86_64
    build:
      context: .
    ports:
      - "3080:3000"
    container_name: stminaclinic-api
    volumes:
       - ./src:/usr/src/app/src
       - ./migrations:/user/src/app/migrations
       - ./config:/user/src/app/config
       - ./models:/user/src/app/models
networks:
  new:

